reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
osx_image: xcode8
before_install: true
install: true
cache: bundler
script:
- script/cibuild
branches:
  only:
  - master
notifications:
  slack:
    secure: UIG9+o5gRYZGpRRBIB/9nFBoXvSOI3Ll63KuUMd/u/CvFpByLY0MSX5LY18v6hYqA3UNjEhOO9x1j91H7JOjbI0NYtq/7+qehUDWORaQc+NSUozKLmkIGm1M6RYayUw61J9fYpyt8AjpbGIb78i7T8ckz7dYkyhEJcGz7L+30pw=
env:
  matrix:
    - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="10.0" CARTHAGE_BUILD_PLATFORM="iOS"
    # - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="9.3" CARTHAGE_BUILD_PLATFORM="iOS"
    # - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="9.2" CARTHAGE_BUILD_PLATFORM="iOS"
    # - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="9.1" CARTHAGE_BUILD_PLATFORM="iOS"
    # - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="9.0" CARTHAGE_BUILD_PLATFORM="iOS"
    - SCHEME="JWTDecode-tvOS" CARTHAGE_BUILD_PLATFORM="tvOS"
    - SCHEME="JWTDecode-OSX" CARTHAGE_BUILD_PLATFORM="Mac"
  global:
  - secure: hHc0uhSg57mTBfFUX7ZwZe85IlLMS+mMgOx192fnVyeD81S2AFxaO4nWRpXHktkR68HwDsYJ4emVeoaLxZb8tkkej+nf1L3NIY3FFEJpIEAmrYMv9AoFb0ZtT1IwGOt92bll0DqzZotOVOrPVZeS8MspwZAFqXHAgBszfJut/2w=
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'JWTDecode'