blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Help & Questions
    url: https://community.auth0.com
    about: Ask general support or usage questions in the Auth0 Community forums
  - name: ðŸš€ Usage
    url: https://github.com/auth0/JWTDecode.swift#usage
    about: Check the Usage section of the README to get up to speed with JWTDecode.swift
  - name: ðŸ“– API Documentation
    url: https://auth0.github.io/JWTDecode.swift/documentation/jwtdecode
    about: Check the public API documentation for in-depth overview of all the available features
